apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: MongoStateful
  namespace: apka
spec:
  serviceName: "mongodb"
  replicas: 2
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongo
        image: mongo:latest
        ports:
        - containerPort: 27017
          name: mongodb
        volumeMounts:
        - name: mongodb-data
          mountPath: /data/db
        env:
        - name: DATABASE_URL
          value: "mongodb://mongo:27017"
     initContainers:
        - name: check-backup
          image: busybox:latest
          command: ["sh", "-c", "if [ -e /data/backup/example.txt ]; then cp -r /data/backup /data/db; else echo 'Plik nie istnieje'; fi"]
          volumeMonunts:
          - name: backup-volmue
            mountPath: /data/backup
  volumeClaimTemplates:
  - metadata:
      name: mongo-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 500Mi
